# Generated by Django 4.2 on 2023-06-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='sem',
            field=models.EmailField(max_length=2),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
