# Generated by Django 4.2 on 2023-06-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_subjects_sem_alter_subjects_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='credits',
            field=models.CharField(default='default_value', max_length=20),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='designation',
            field=models.CharField(default='default_value', max_length=20),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='sem',
            field=models.CharField(default='default_value', max_length=20),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='type',
            field=models.CharField(default='default_value', max_length=20),
        ),
    ]
