# Generated by Django 4.2.1 on 2023-06-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_subjects_credits_alter_instructor_designation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='type',
            new_name='stype',
        ),
    ]
