# Generated by Django 4.2.1 on 2023-06-14 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_type_subjects_stype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='stype',
            new_name='type',
        ),
    ]
