# Generated by Django 4.2.1 on 2023-06-14 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_stype_subjects_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='type',
            new_name='stype',
        ),
    ]
