# Generated by Django 4.2.1 on 2023-06-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_subjects_code_alter_subjects_name'),
        ('home', '0009_alter_subjects_stype'),
    ]

    operations = [
    ]
