# Generated by Django 4.2 on 2023-06-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_merge_20230614_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='designation',
            field=models.CharField(default='professor', max_length=20),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='credits',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='sem',
            field=models.CharField(default='3', max_length=20),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='stype',
            field=models.CharField(default='2', max_length=20, null=True),
        ),
    ]
