# Generated by Django 4.2.1 on 2023-06-16 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_theory_instructor_remove_theory_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='theory',
            name='instructor',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='home.instructor'),
        ),
        migrations.AddField(
            model_name='theory',
            name='subject',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home.subjects'),
        ),
    ]
