# Generated by Django 4.2.1 on 2023-06-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_theory_instructor_theory_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.IntegerField(unique=True)),
                ('room_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
