# Generated by Django 4.2.1 on 2023-06-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='semester_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
