# Generated by Django 4.2.1 on 2023-06-17 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_room_room_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20)),
                ('day', models.PositiveSmallIntegerField()),
                ('slot', models.PositiveSmallIntegerField()),
                ('theory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.theory')),
            ],
        ),
    ]
