# Generated by Django 4.2.1 on 2023-06-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depname', models.CharField(max_length=30)),
                ('courses', models.CharField(max_length=100)),
            ],
        ),
    ]
