# Generated by Django 4.2.1 on 2023-06-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_department_courses_alter_department_depname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='phone',
        ),
        migrations.AlterField(
            model_name='department',
            name='depname',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering')], max_length=30),
        ),
    ]
