# Generated by Django 4.2.1 on 2023-06-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_meetingtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='seating_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
