# Generated by Django 4.2.1 on 2023-06-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_subjects_max_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='instructors',
            field=models.ManyToManyField(to='home.instructor'),
        ),
    ]
