# Generated by Django 4.2.1 on 2023-06-18 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_subjects_instructors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='name',
            new_name='sname',
        ),
    ]
