# Generated by Django 4.2.1 on 2023-06-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_rename_name_subjects_sname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
