# Generated by Django 4.2.1 on 2023-06-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_remove_department_courses_department_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtime',
            name='duration',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='time',
            field=models.CharField(choices=[('8:00 - 9:00', '8:00 - 9:00'), ('9:00 - 10:00', '9:00 - 10:00'), ('10:30 - 11:30', '10:30 - 11:30'), ('11:30 - 12:30', '11:30 - 12:30'), ('2:00 - 3:00', '2:00 - 3:00'), ('2:00 - 5:00', '2:00 - 5:00'), ('10:15 - 1:15', '10:15 - 1:15'), ('3:00 - 4:00', '3:00 - 4:00'), ('4:00 - 5:00', '4:00 - 5:00')], default='11:30 - 12:30', max_length=50),
        ),
    ]
