# Generated by Django 4.2.1 on 2023-06-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_meetingtime_duration_alter_meetingtime_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='rtype',
            field=models.CharField(default='lab', max_length=20, null=True),
        ),
    ]
