# Generated by Django 4.2.1 on 2023-06-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_classroom_rtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='rtype',
            field=models.CharField(default='Theory', max_length=20, null=True),
        ),
    ]
