# Generated by Django 4.2.1 on 2023-06-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_classroom_rtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='lab_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
